default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: video-manager_development

test:
  <<: *default
  database: video-manager_test

production:
  <<: *default
  database: video-manager_production
  username: video-manager
  password: <%= ENV['VIDEO-MANAGER_DATABASE_PASSWORD'] %>
